-- auto-generated definition
create table if not exists customer
(
    id                 bigint generated by default as identity primary key,
    name              varchar(255) not null,
    surname              varchar(255) not null,
    credit_limit              DOUBLE,
    used_credit_limit              DOUBLE
    );


create table if not exists loan
(
    id              bigint generated by default as identity primary key,
    customer_id     bigint not null constraint fk_customer_id references customer,
    loan_amount     DOUBLE,
    interest_rate     FLOAT,
    number_of_installment     int,
    create_date     timestamp,
    paid            boolean
);

create table if not exists installment
(
    id              bigint generated by default as identity primary key,
    loan_id     bigint not null constraint fk_loan_id references loan,
    amount     DOUBLE,
    paid_amount     DOUBLE,
    due_date     timestamp,
    payment_date     timestamp,
    paid            boolean
);
